name: my-workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build project
        run:  gradle clean build

  checkstyle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run jacoco report
        run:  gradle jacocoTestReport
      - name: Upload jacoco report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          files: '/build/reports/jacoco/test/jacocoTestReport.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Results
          update-comment: true
